Add Discord identifier fields to the Team table
python-discord/code-jam-management pull request #14
Opened 2022-06-30 11:57 UTC by D0rs4n

- Add `discord_role_id` to the Team table
- Add `discord_channel_id` to the Team table
- Update Models accordingly

2022-06-30 12:14 UTC, ChrisLovering commented on tests/routers/conftest.py
> +        client: AsyncClient, codejam: models.CodeJam, session: AsyncSession
what caused the extra indent here and below? Are we running some formatter now?

2022-06-30 12:18 UTC, ChrisLovering approved these changes

2022-06-30 12:46 UTC, ks129 approved these changes
Intents are weird but otherwise OK.

2022-06-30 12:49 UTC, ChrisLovering requested changes

2022-06-30 13:51 UTC, ChrisLovering approved these changes

2022-06-30 13:51 UTC, merged

2024-09-27 18:17 UTC, ChrisLovering commented
Thanks

2024-09-27 18:17 UTC, fisher60 commented
Code cov looks good now. Appropriate covered lines.